version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 1
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
    day: "sunday"
  open-pull-requests-limit: 2
