name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  postgresql_16:
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 16
  postgresql_15:
    needs: [postgresql_16]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 15
      python-versions: '["3.9", "3.10", "3.11", "3.12"]'
  postgresql_14:
    needs: [postgresql_15]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 14
      python-versions: '["3.10", "3.11", "3.12"]'
  postgresql_13:
    needs: [postgresql_14]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 13
      python-versions: '["3.12"]'
  postgresql_12:
    needs: [postgresql_13]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 12
      python-versions: '["3.12"]'
  macos_postgres_16:
    needs: [postgresql_16]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 16
      os: macos-latest
      python-versions: '["3.9", "3.10", "3.11", "3.12"]'
  macos_postgres_15:
    needs: [postgresql_15, macos_postgres_16]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 15
      os: macos-latest
      python-versions: '["3.10", "3.11", "3.12"]'
  macos_postgres_14:
    needs: [postgresql_14, macos_postgres_15]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 14
      os: macos-latest
      python-versions: '["3.11", "3.12"]'
  docker_postgresql_16:
    needs: [postgresql_16]
    uses: ./.github/workflows/dockerised-postgres.yml
    with:
      postgresql: 16
  docker_postgresql_15:
    needs: [postgresql_15, docker_postgresql_16]
    uses: ./.github/workflows/dockerised-postgres.yml
    with:
      postgresql: 15
      python-versions: '["3.9", "3.10", "3.11", "3.12"]'
  docker_postgresql_14:
    needs: [postgresql_14, docker_postgresql_15]
    uses: ./.github/workflows/dockerised-postgres.yml
    with:
      postgresql: 14
      python-versions: '["3.10", "3.11", "3.12"]'
  docker_postgresql_13:
    needs: [postgresql_13, docker_postgresql_14]
    uses: ./.github/workflows/dockerised-postgres.yml
    with:
      postgresql: 13
      python-versions: '["3.11", "3.12"]'
  docker_postgresql_12:
    needs: [postgresql_12, docker_postgresql_13]
    uses: ./.github/workflows/dockerised-postgres.yml
    with:
      postgresql: 12
      python-versions: '["3.12"]'
