name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, pypy3]
    env:
      OS: ubuntu-latest
      PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    - name: Run test
      run: |
        py.test -n 0 --cov-report=xml
    - name: Run xdist test
      run: |
        py.test -n 1 --cov-report=xml:coverage-xdist.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml ./coverage-xdist.xml
        flags: unittests
        env_vars: OS,PYTHON
        fail_ci_if_error: true
