name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  postgresql_15:
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 15
  postgresql_14:
    needs: [postgresql_15]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 14
  postgresql_13:
    needs: [postgresql_14]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 13
  postgresql_12:
    needs: [postgresql_13]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 12
  postgresql_11:
    needs: [postgresql_12]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 11
  macos_postgres_15:
    needs: [postgresql_15]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 15
      os: macos-latest
  macos_postgres_14:
    needs: [postgresql_14, macos_postgres_15]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 14
      os: macos-latest
  macos_postgres_13:
    needs: [postgresql_13, macos_postgres_14]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 13
      os: macos-latest
  docker_postgresql_15:
    needs: [postgresql_15]
    uses: ./.github/workflows/dockerised-postgres.yml
    with:
      postgresql: 15
  docker_postgresql_14:
    needs: [postgresql_14, docker_postgresql_15]
    uses: ./.github/workflows/dockerised-postgres.yml
    with:
      postgresql: 14
  docker_postgresql_13:
    needs: [postgresql_13, docker_postgresql_14]
    uses: ./.github/workflows/dockerised-postgres.yml
    with:
      postgresql: 13
  docker_postgresql_12:
    needs: [postgresql_12, docker_postgresql_13]
    uses: ./.github/workflows/dockerised-postgres.yml
    with:
      postgresql: 12
  docker_postgresql_11:
    needs: [postgresql_11, docker_postgresql_12]
    uses: ./.github/workflows/dockerised-postgres.yml
    with:
      postgresql: 11
